### PR TITLE
Improvement value-list-comma-newline-*

### PR DESCRIPTION
**Pull request by matijs**
Prettier is opinionated about this so let Prettier fix this.

### CODE REVIEW

**Comment by matijs** [comment]
Not merging this just yet as @ImreBognarUltimaker is looking into it.

**Comment by matijs** [comment]
@ianpaschal as @ImreBognarUltimaker is off on holidays, could you have a look at this? You also have thoughts on the use of Prettier that are relevant to this specific case.

**Comment by ianpaschal** [comment]
I don't want to have to use Prettier as it doesn't add anything to my work that other tools don't. If I'm reading this right, it looks like you're forcing the use of Prettier to get the correct results.

**Comment by ianpaschal** [comment]
@matijs Sorry, I should have used 'Request Changes' but I was hoping you'd answer my question before merging.

**Pull request merged**
